title: Kyeongju BLOG
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: Kyeongju
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: ainimo2@gmail.com

google_analytics: "UA-138368808-1"
disqus-shortname: Kyeongju
